# #12 Highly Divisible Triangular Number

# The sequence of triangle numbers is generated by adding the natural numbers. 
# So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. 

# The first ten terms would be: 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

# Let us list the factors of the first seven triangle numbers:

#  1: 1
#  3: 1,3
#  6: 1,2,3,6
# 10: 1,2,5,10
# 15: 1,3,5,15
# 21: 1,3,7,21
# 28: 1,2,4,7,14,28
# We can see that 28 is the first triangle number to have over five divisors.

# What is the value of the first triangle number to have over five hundred divisors? 

# answer = 76576500

def get_num divisors

  num = 1
  num_iter = 1
  i = 1
  count = 0
  limit = num
  answer = 0

  while answer == 0 do

    while i < limit do
      if num % i == 0
        if num / i > i
          count += 2
          limit = num / i
        else
          count += 1
        end
      end
          
      i += 1 
    end

    if count < divisors
      num_iter += 1
      i = 1
      num += num_iter
      limit = num
      count = 0
    else
      answer = num
    end
  end

  answer
end

puts get_num 500
