# Triangular, pentagonal, and hexagonal
# Problem 45

# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

# Triangle    Tn=n(n+1)/2   1, 3, 6, 10, 15, ...
# Pentagonal    Pn=n(3n−1)/2    1, 5, 12, 22, 35, ...
# Hexagonal   Hn=n(2n−1)    1, 6, 15, 28, 45, ...
# It can be verified that T285 = P165 = H143 = 40755.

# Find the next triangle number that is also pentagonal and hexagonal.
# answer: 1533776805
# time: .143 s

def tri_pent_hex

  hex = Enumerator.new do |y|
    h = 144
    loop do 
      y << h * (2 * h - 1)
      h += 1
    end
  end

  while true do 
    num = hex.next
    return num if pent_check(num) && tri_check(num)
  end
end

def pent_check(num)
  return true if (Math.sqrt(24 * num + 1) + 1) % 6 == 0
end

def tri_check(num)
  return true if (Math.sqrt(8 * num + 1) + 1) % 2 == 0
end

puts tri_pent_hex

