# Pentagon numbers
# Problem 44

# Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. 
# The first ten pentagonal numbers are:

# 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

# It can be seen that P4 + P7 = 22 + 70 = 92 = P8. 
# However, their difference, 70 − 22 = 48, is not pentagonal.

# Find the pair of pentagonal numbers, Pj and Pk, 
# for which their sum and difference are pentagonal 
#   and D = |Pk − Pj| is minimised; what is the value of D?

# 7042750 & 1560090 are answer 2 min, 35 sec!

def pentagon
  answer = 0
  pent_array = []
  
  # pentagonal number enumerator
  pent = Enumerator.new do |y|
    n = 1
    loop do 
      p = (n * (3 * n - 1)) / 2
      y << p
      n += 1
    end
  end

  until answer > 0 do
    num1 = pent.next
    
    pent_array.each do |num2|
      puts "#{num1},#{num2}"
      if pent_array.include?(num1 - num2) && pent_check(num1, num2)
      
      answer = num1 - num2
      puts answer

      end
    end

    pent_array << num1
  end
end


def pent_check(num1, num2) 
  sum = num1 + num2

  # pentagonal number enumerator
  check = Enumerator.new do |y|
    n = 1
    loop do 
      p = (n * (3 * n - 1)) / 2
      y << p
      n += 1
    end
  end

  # looks for num in enum of pentagonal numbers
  x = 0

  until x >= sum do 
    x = check.next
  end
  
  return true if sum == x
 
end

puts pentagon