// Even Fibonacci numbers
// Problem 2
// Each new term in the Fibonacci sequence is generated by
// adding the previous two terms. By starting with 1 and 2,
// the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values
// do not exceed four million, find the sum of the even-valued terms.

// answer: 4613732
// run time:.221

package main

import "fmt"

func Fibsequence() int {
	a, b, sum := 1, 0, 0
	for a < 4000000 {
		fib := a + b
		if fib%2 == 0 {
			sum += fib
		}
		a, b = fib, a
	}
	return sum
}

func main() {
	fmt.Println(Fibsequence())
}
