# Even Fibonacci numbers
# Problem 2

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

# answer: 4613732
# time: .023s

def fib_sum(limit):
    even_sum = 0

    first_term = 1
    second_term = 1
    
    while second_term <= limit:
        new_term = first_term + second_term
        
        if new_term % 2 == 0:
            even_sum += new_term

        first_term = second_term
        second_term = new_term
    else:
        return even_sum

print fib_sum(4000000)